[InstallShield Silent]
Version=v6.00.000
File=Response File
[File Transfer]
OverwrittenReadOnly=NoToAll
[{FB08F381-6533-4108-B7DD-039E11FBC27E}-DlgOrder]
Dlg0={FB08F381-6533-4108-B7DD-039E11FBC27E}-SdWelcome-0
Count=2
Dlg1={FB08F381-6533-4108-B7DD-039E11FBC27E}-SdFinishReboot-0
[{FB08F381-6533-4108-B7DD-039E11FBC27E}-SdWelcome-0]
Result=1
[Application]
Name=Avance AC'97 Audio
Version=4.50
Company=Avance Logic, Inc.
Lang=0009
[{FB08F381-6533-4108-B7DD-039E11FBC27E}-SdFinishReboot-0]
Result=1
BootOption=0
